version: "3.9"

services:

  nginx:
    image: nginx:alpine
    container_name: novasafe-nginx
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./cloudflare:/etc/nginx/cloudflare

    networks:
      - novasafe-network

    restart: unless-stopped

networks:
  novasafe-network:
    external: true