services:

  backend:

    image: ghcr.io/novasafe-org/novasafe-backend:latest

    container_name: novasafe-backend

    env_file:
      - .env

    networks:
      - novasafe-network

    restart: unless-stopped

networks:
  novasafe-network:
    external: true